# Generated by Django 4.1.3 on 2022-12-01 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_share_post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='image'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Like', to='img_share_post.upload', verbose_name='upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Upload_like', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
