# Generated by Django 4.1.3 on 2022-12-01 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_share_post', '0002_alter_upload_image_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=200, verbose_name='comment')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='img_share_post.upload', verbose_name='upload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
