# Generated by Django 4.1.3 on 2022-12-11 10:22

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('img_share_post', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description'),
        ),
    ]
