# Generated by Django 4.1.3 on 2022-12-11 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import img_share_post.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('img_share_post', '0004_alter_upload_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'ordering': ['published'], 'verbose_name_plural': 'Series'},
        ),
        migrations.RemoveField(
            model_name='upload',
            name='description',
        ),
        migrations.RemoveField(
            model_name='upload',
            name='user',
        ),
        migrations.AddField(
            model_name='upload',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='upload',
            name='published',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date published'),
        ),
        migrations.AddField(
            model_name='upload',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, unique=True, verbose_name='Series slug'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='upload',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='upload',
            name='image',
            field=models.ImageField(blank=True, default='default/cat_sit.jpg', null=True, upload_to=img_share_post.models.Upload.image_upload),
        ),
        migrations.AlterField(
            model_name='upload',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('post_slug', models.SlugField(unique=True, verbose_name='Post slug')),
                ('content', tinymce.models.HTMLField(blank=True, default='')),
                ('notes', tinymce.models.HTMLField(blank=True, default='')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created')),
                ('modified', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Modified')),
                ('image', models.ImageField(blank=True, default='default/cat_sit.jpg', null=True, upload_to=img_share_post.models.Post.image_upload)),
                ('poster', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
                ('series', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='img_share_post.upload', verbose_name='Series')),
            ],
            options={
                'verbose_name_plural': 'Post',
                'ordering': ['published'],
            },
        ),
    ]
